export const MAP_ASSET_KEYS = Object.freeze({
    MAP: 'MAP_ASSET_KEYS.MAP',
    BLANK: 'MAP_ASSET_KEYS.BLANK',
    UNIT: 'MAP_ASSET_KEYS.UNIT',
    SELECTION: 'MAP_ASSET_KEYS.SELECTION',
    FRAME_FONT: 'MAP_ASSET_KEYS.FRAME_FONT',
});
